name: CI-CD-PaintingsProject

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE: diplomeproject/paintingsproject-frontend
  BACKEND_IMAGE: diplomeproject/paintingsproject-backend

jobs:
# =====================
# CI ‚Äî BUILD & PUSH
# =====================
  build:
  
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest


      # ---------- BACKEND ----------
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

# =====================
# CD ‚Äî DEPLOY
# =====================
  deploy:
    needs: build
    runs-on: self-hosted
    environment: test-srv

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "üîê Login to GHCR"
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            echo "üåê Create docker network"
            docker network create paintings-net || true

            echo "‚¨á Pull latest images"
            docker pull ghcr.io/diplomeproject/paintingsproject-frontend:latest
            docker pull ghcr.io/diplomeproject/paintingsproject-backend:latest

            echo "üõë Stop old containers"
            docker stop frontend backend || true
            docker rm frontend backend || true

            echo "üöÄ Start backend container"
            docker run -d \
              --name backend \
              --network paintings-net \
              ghcr.io/diplomeproject/paintingsproject-backend:latest

            echo "üöÄ Start frontend container (PUBLIC)"
            docker run -d \
              --name frontend \
              --network paintings-net \
              -p 8080:80 \
              ghcr.io/diplomeproject/paintingsproject-frontend:latest

            echo "‚úÖ Application available at http://172.17.3.24:8080"
